name: gia_pdg_partenaire
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.19.0
  qr_code_scanner: ^1.0.1
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  location: ^5.0.3
  http: ^1.2.0
  google_maps_flutter: ^2.5.3
  pinput: ^3.0.1
  flutter_local_notifications: ^16.3.3
  flutter_badged: ^2.0.3
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  dio: ^5.4.1
  path_provider: ^2.1.2
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/img/flags/
    - assets/img/africa_flag/
    - assets/img/icons/
    - assets/img/logo/
  
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/static/Manrope-ExtraLight.ttf
        - asset: assets/fonts/static/Manrope-Light.ttf
        - asset: assets/fonts/static/Manrope-Regular.ttf
        - asset: assets/fonts/static/Manrope-Medium.ttf
        - asset: assets/fonts/static/Manrope-SemiBold.ttf
        - asset: assets/fonts/static/Manrope-Bold.ttf
        - asset: assets/fonts/static/Manrope-ExtraBold.ttf

